service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  region: ap-northeast-1
  memorySize: 256

  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:*
    Resource:
    - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  hello:
    handler: build/handler.hello
    events:
      - http:
          method: get
          path: hello
  post:
    handler: build/handler.post
    events:
      - http:
          method: post
          path: hello
  getData:
    handler: build/handler.getData
    events:
      - http:
          method: get
          path: data
  postData:
    handler: build/handler.postData
    events:
      - http:
          method: post
          path: data
